pipeline:
  name: React app - Lint and Test - Single Stage
  identifier: React_app_Lint_and_Test
  projectIdentifier: Product_Exploratory
  orgIdentifier: default
  tags: {}
  properties:
    ci:
      codebase:
        connectorRef: account.tejakummarikuntla
        repoName: gh-actions-artifacts
        build: <+input>
  stages:
    - stage:
        name: Get Codebase
        identifier: Run_Lints
        description: ""
        type: CI
        spec:
          cloneCodebase: true
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          caching:
            enabled: false
            paths: []
          slsa_provenance:
            enabled: false
          execution:
            steps:
              - step:
                  type: Run
                  name: Install dependencies
                  identifier: Install_dependencies
                  spec:
                    shell: Sh
                    command: npm ci
              - step:
                  type: Run
                  name: Lint code
                  identifier: Lint_code
                  spec:
                    shell: Sh
                    command: npm run lint
              - step:
                  type: Run
                  name: Test code
                  identifier: Test_code
                  spec:
                    shell: Sh
                    command: npm run test
        when:
          pipelineStatus: Success
    - stage:
        name: Build and push to Docker
        identifier: Build_and_push_to_Docker
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: SscaOrchestration
                  name: SscaOrchestration_1
                  identifier: SscaOrchestration_1
                  spec:
                    attestation:
                      type: cosign
                      spec:
                        privateKey: Teja_CoSign_Key
                        password: Teja_Cosing_Password
                    source:
                      type: image
                      spec:
                        connector: tejakummarikutla
                        image: tejakummarikuntla/rabbitmq_eventexchange
                    tool:
                      type: Syft
                      spec:
                        format: spdx-json
                    mode: generation
                    resources:
                      limits:
                        memory: 500Mi
                        cpu: "0.5"
          caching:
            enabled: false
            paths: []
          slsa_provenance:
            enabled: false
    - stage:
        name: SBOM Generation
        identifier: SBOM_Generation
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          platform:
            os: Linux
            arch: Arm64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: SscaOrchestration
                  name: SscaOrchestration_1
                  identifier: SscaOrchestration_1
                  spec:
                    attestation:
                      type: cosign
                      spec:
                        privateKey: Teja_CoSign_Key
                        password: Teja_Cosing_Password
                    source:
                      type: image
                      spec:
                        connector: tejakummarikutla
                        image: tejakummarikuntla/apihub/
                    sbom_drift:
                      base: last_generated_sbom
                    tool:
                      type: Syft
                      spec:
                        format: spdx-json
                    mode: generation
                    resources:
                      limits:
                        memory: 500Mi
                        cpu: "0.5"
